# Generated by Django 5.2.8 on 2025-12-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_idempotencykey'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcard',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savedcard',
            name='last_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
