# Generated by Django 5.2.8 on 2025-12-31 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_wallet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('SAVINGS', 'Savings'), ('THRIFT', 'Thrift')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('unlock_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_plans', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_plans', to='payments.wallet')),
            ],
        ),
    ]
