# Generated by Django 5.2.8 on 2026-01-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_savingsplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingsplan',
            old_name='unlock_at',
            new_name='locked_until',
        ),
        migrations.RemoveField(
            model_name='savingsplan',
            name='is_unlocked',
        ),
        migrations.AddField(
            model_name='savingsplan',
            name='broken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savingsplan',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='savingsplan',
            name='status',
            field=models.CharField(choices=[('locked', 'Locked'), ('unlocked', 'Unlocked'), ('broken', 'Broken Early')], default='locked', max_length=20),
        ),
        migrations.AddField(
            model_name='savingsplan',
            name='unlocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='savingsplan',
            name='plan_type',
            field=models.CharField(choices=[('SAVINGS', 'Savings'), ('THRIFT', 'Thrift')], default='SAVINGS', max_length=20),
        ),
    ]
