# Generated by Django 5.2.8 on 2026-01-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_rename_unlock_at_savingsplan_locked_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='nuban_account_name',
            field=models.CharField(blank=True, help_text='Account name assigned by Providus', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='nuban_account_number',
            field=models.CharField(blank=True, help_text='Virtual NUBAN account number from Providus', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='providus_customer_id',
            field=models.CharField(blank=True, help_text='Customer reference ID from Providus', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='providus_ref',
            field=models.CharField(blank=True, help_text='Reference used for recon and webhook routing', max_length=100, null=True),
        ),
    ]
