# Generated by Django 5.2.8 on 2025-11-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_post_limit',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='plan_type',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], default='BASIC', max_length=20),
        ),
    ]
