# Generated by Django 5.2.8 on 2025-12-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_paystacktransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_channel',
            field=models.CharField(blank=True, choices=[('EMAIL', 'Email'), ('PHONE', 'Phone')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
