# Generated by Django 5.2.8 on 2026-01-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_otp_channel_user_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('ARTISAN', 'Artisan'), ('COMPANY', 'Company')], default='CLIENT', max_length=20),
        ),
    ]
