# Generated by Django 5.0.3 on 2025-11-11 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Job Post', 'verbose_name_plural': 'Job Posts'},
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='address',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='is_remote',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='position_title',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='url',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='verified_user',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='company_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_mode',
            field=models.CharField(choices=[('ONSITE', 'On-site'), ('REMOTE', 'Remote'), ('HYBRID', 'Hybrid')], default='ONSITE', max_length=16),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='plan_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], default='basic', max_length=16),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='role',
            field=models.CharField(default='General', max_length=200),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='salary_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract')], default='Full-Time', max_length=32),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='source',
            field=models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], default='INTERNAL', max_length=16),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
