# Generated by Django 5.2.8 on 2025-12-01 14:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_savingsotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='savings',
            name='interest_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='savings',
            name='interest_rate',
            field=models.FloatField(default=0.05),
        ),
        migrations.AddField(
            model_name='savings',
            name='last_interest_applied',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
