# Generated by Django 5.2.8 on 2025-12-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0004_savings_interest_earned_savings_interest_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savings',
            name='goal_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savings',
            name='target_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
