# Generated by Django 5.2.8 on 2025-11-12 17:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('Google', 'Google'), ('Jobberman', 'Jobberman'), ('Indeed', 'Indeed'), ('All', 'All Sources')], default='All', max_length=50)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=10)),
                ('new_jobs', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True, null=True)),
                ('run_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Job Sync Log',
                'verbose_name_plural': 'Job Sync Logs',
                'ordering': ['-run_time'],
            },
        ),
    ]
